/**
 * @file ui_assets.h
 * @brief UI image assets (generated by scripts/embed_ui_assets.sh).
 */

#pragma once

#include "lvgl.h"
#include "esp_err.h"

/** Mount SPIFFS (storage partition) and prepare LVGL S: drive paths. */
esp_err_t ui_assets_init(void);

/** LVGL file path for a SPIFFS asset, e.g. "S:/tod_wake.bin". */
const char *ui_assets_spiffs_path(const char *name);

/** Reusable white icon glyphs (RGB565A8, tight crop). */
/** White left-arrow glyph for wedge buttons */
extern const lv_image_dsc_t icon_arrow_left;

/** White right-arrow glyph for wedge buttons */
extern const lv_image_dsc_t icon_arrow_right;

/** White cancel (X) glyph for wedge buttons */
extern const lv_image_dsc_t icon_cancel;

/** White check glyph for wedge buttons */
extern const lv_image_dsc_t icon_check;

/** White spanner glyph for wedge buttons */
extern const lv_image_dsc_t icon_spanner;

/** A8 wedge silhouettes — tint at runtime via image_recolor. */
/** A8 wedge silhouette (left) — tint at runtime via image_recolor */
extern const lv_image_dsc_t wedge_shape_left;

/** A8 wedge silhouette (right) — tint at runtime via image_recolor */
extern const lv_image_dsc_t wedge_shape_right;

/** A8 wide bottom wedge silhouette — tint at runtime via image_recolor */
extern const lv_image_dsc_t wedge_shape_wide;

