/**
 * @file ui_assets.h
 * @brief UI image assets (generated by scripts/embed_ui_assets.sh).
 */

#pragma once

#include "lvgl.h"
#include "esp_err.h"

/** Mount SPIFFS (storage partition) and prepare LVGL S: drive paths. */
esp_err_t ui_assets_init(void);

/** LVGL file path for a SPIFFS asset, e.g. "S:/tod_wake.bin". */
const char *ui_assets_spiffs_path(const char *name);

/** White icon overlays, composed on top of a wedge button. */
/** White cancel icon overlay for wedge buttons */
extern const lv_image_dsc_t icon_wedge_cancel;

/** White confirm icon overlay for wedge buttons */
extern const lv_image_dsc_t icon_wedge_confirm;

/** White menu icon overlay for wide wedge button */
extern const lv_image_dsc_t icon_wedge_menu_wide;

/** White next-arrow icon overlay for wedge buttons */
extern const lv_image_dsc_t icon_wedge_next;

/** White settings icon overlay for wedge buttons */
extern const lv_image_dsc_t icon_wedge_settings;

/** A8 wedge silhouettes — tint at runtime via image_recolor. */
/** A8 wedge silhouette (left) — tint at runtime via image_recolor */
extern const lv_image_dsc_t wedge_shape_left;

/** A8 wedge silhouette (right) — tint at runtime via image_recolor */
extern const lv_image_dsc_t wedge_shape_right;

/** A8 wide bottom wedge silhouette — tint at runtime via image_recolor */
extern const lv_image_dsc_t wedge_shape_wide;

