/**
 * @file ui_assets.h
 * @brief Embedded LVGL image descriptors (generated by scripts/embed_ui_assets.sh).
 */

#pragma once

#include "lvgl.h"

/** Button to start a rest */
extern const lv_image_dsc_t btn_start_rest;

/** Button to start a sleep */
extern const lv_image_dsc_t btn_start_sleep;

/** Button to start timer */
extern const lv_image_dsc_t btn_start_timer;

/** Button to end sleep / rest */
extern const lv_image_dsc_t btn_start_wake;

/** White icon overlays, composed on top of a wedge button. */
/** White cancel icon overlay for wedge buttons */
extern const lv_image_dsc_t icon_wedge_cancel;

/** White confirm icon overlay for wedge buttons */
extern const lv_image_dsc_t icon_wedge_confirm;

/** White menu icon overlay for wide wedge button */
extern const lv_image_dsc_t icon_wedge_menu_wide;

/** White next-arrow icon overlay for wedge buttons */
extern const lv_image_dsc_t icon_wedge_next;

/** White settings icon overlay for wedge buttons */
extern const lv_image_dsc_t icon_wedge_settings;

/** Splash screen (720×720 RGB565) */
extern const lv_image_dsc_t splash;

/** Full-screen Time of Day backgrounds (720×720 RGB565). */
/** Time of Day background — rest */
extern const lv_image_dsc_t tod_rest;

/** Time of Day background — sleep */
extern const lv_image_dsc_t tod_sleep;

/** Time of Day background — wake */
extern const lv_image_dsc_t tod_wake;

/** Time of Day background — wind down */
extern const lv_image_dsc_t tod_winddown;

/** A8 wedge silhouettes — tint at runtime via image_recolor. */
/** A8 wedge silhouette (left) — tint at runtime via image_recolor */
extern const lv_image_dsc_t wedge_shape_left;

/** A8 wedge silhouette (right) — tint at runtime via image_recolor */
extern const lv_image_dsc_t wedge_shape_right;

/** A8 wide bottom wedge silhouette — tint at runtime via image_recolor */
extern const lv_image_dsc_t wedge_shape_wide;

